- platform: foscam
  ip: 10.10.20.120
  username: !secret foscam_user
  password: !secret foscam_pass
  port: 88
- platform: mjpeg
  name: OctoPrint
  still_image_url: http://10.10.20.10/webcam/?action=snapshot
  mjpeg_url: http://10.10.20.10/webcam/?action=stream