
#Sala
- platform: generic_thermostat
  name: Aquecedor da Sala
  heater: switch.aquecedor_da_sala
  target_sensor: sensor.living_room_temp

#Escritório
# - platform: generic_thermostat
#   name: Office Climate
#   heater: light.study_lamp
#   target_sensor: sensor.office_temp

#Quarto
- platform: smartir
  name: Ar condicionado do quarto
  unique_id: bedroom_ac
  device_code: 1285
  controller_data: remote.broadlink_quarto_remote
  temperature_sensor: sensor.bedroom_sensor
  humidity_sensor: sensor.bedroom_sensor_2
  power_sensor: binary_sensor.ac_power

# - platform: midea_ac
#   host: 10.10.20.119
#   id: 19791209335791

- platform: midea
  app_key: 3742e9e5842d4ad59c2db887e12449f9
  username: 'contact@ulisses.xyz'
  password: !secret midea_password
  use_fan_only_workaround: true
