- platform: androidtv
  host: 10.10.20.3
  name: 'Televisão do Quarto'
  adb_server_ip: 127.0.0.1
    
- platform: kodi
  host: 10.10.20.3


- platform: smartir
  name: Televisão da Sala
  unique_id: living_room_tv
  device_code: 1000
  controller_data: remote.broadlink_sala_remote
  power_sensor: binary_sensor.tv_power