############################################################
#            Send Notifications to Pushbullet App          #
############################################################

- platform: pushbullet
  name: Alfred
  api_key: !secret pushbullet_api_key

- platform: nfandroidtv
  name: Quarto
  host: 10.10.20.2