- platform: mqtt
  name: 'Sonoff 1'
  command_topic: 'cmnd/sonoff_1/power'
  state_topic: 'stat/sonoff_1/POWER'
  qos: 1
  payload_on: 'ON'
  payload_off: 'OFF'
  retain: true

- platform: mqtt
  name: 'Microwave'
  command_topic: 'cmnd/microwave/power'
  state_topic: 'stat/microwave/POWER'
  qos: 1
  payload_on: 'ON'
  payload_off: 'OFF'
  retain: true


- platform: mqtt
  name: 'Oven'
  command_topic: 'cmnd/oven/power'
  state_topic: 'stat/oven/POWER'
  qos: 1
  payload_on: 'ON'
  payload_off: 'OFF'
  retain: true
  
- platform: mqtt
  name: 'Tomada do Aquecedor da Sala'
  command_topic: 'cmnd/heater/power'
  state_topic: 'stat/heater/POWER'
  qos: 1
  payload_on: 'ON'
  payload_off: 'OFF'
  retain: true

- platform: mqtt
  name: 'Desumidificador'
  command_topic: 'cmnd/sonoff_dehu/power'
  state_topic: 'stat/sonoff_dehu/POWER'
  qos: 1
  payload_on: 'ON'
  payload_off: 'OFF'
  retain: true

- platform: mqtt
  name: 'Aquecedor de Toalhas'
  command_topic: 'cmnd/sonoff_bathroom/power'
  state_topic: 'stat/sonoff_bathroom/POWER'
  qos: 1
  payload_on: 'ON'
  payload_off: 'OFF'
  retain: true

- platform: mqtt
  name: 'Luz da impressora'
  command_topic: 'cmnd/anet/power'
  state_topic: 'stat/anet/POWER'
  qos: 1
  payload_on: 'ON'
  payload_off: 'OFF'
  retain: true

- platform: mqtt
  name: 'Televisão da Sala'
  command_topic: 'cmnd/sonoff_tv_sala/power'
  state_topic: 'stat/sonoff_tv_sala/POWER'
  qos: 1
  payload_on: 'ON'
  payload_off: 'OFF'
  retain: true

- platform: broadlink
  host: 192.168.1.200
  mac: '24:df:a7:4f:d1:94'
  type: rm4c_mini