- platform: mqtt
  name: 'Sonoff 1'
  command_topic: 'home/sonoff/cmnd/sonoff_1/power'
  state_topic: 'home/sonoff/stat/sonoff_1/POWER'
  qos: 1
  payload_on: 'ON'
  payload_off: 'OFF'
  retain: true

- platform: mqtt
  name: 'Microwave'
  command_topic: 'home/sonoff/cmnd/microwave/power'
  state_topic: 'home/sonoff/stat/microwave/POWER'
  qos: 1
  payload_on: 'ON'
  payload_off: 'OFF'
  retain: true


- platform: mqtt
  name: 'Oven'
  command_topic: 'home/sonoff/cmnd/oven/power'
  state_topic: 'home/sonoff/stat/oven/POWER'
  qos: 1
  payload_on: 'ON'
  payload_off: 'OFF'
  retain: true
  
- platform: mqtt
  name: 'Tomada do Aquecedor da Sala'
  command_topic: 'home/sonoff/cmnd/heater/power'
  state_topic: 'home/sonoff/stat/heater/POWER'
  qos: 1
  payload_on: 'ON'
  payload_off: 'OFF'
  retain: true

- platform: mqtt
  name: 'Desumidificador'
  command_topic: 'home/sonoff/cmnd/sonoff_dehu/power'
  state_topic: 'home/sonoff/stat/sonoff_dehu/POWER'
  qos: 1
  payload_on: 'ON'
  payload_off: 'OFF'
  retain: true

- platform: mqtt
  name: 'Aquecedor de Toalhas'
  command_topic: 'home/sonoff/cmnd/sonoff_bathroom/power'
  state_topic: 'home/sonoff/stat/sonoff_bathroom/POWER'
  qos: 1
  payload_on: 'ON'
  payload_off: 'OFF'
  retain: true

- platform: mqtt
  name: 'Luz da impressora'
  command_topic: 'home/sonoff/cmnd/anet/power'
  state_topic: 'home/sonoff/stat/anet/POWER'
  qos: 1
  payload_on: 'ON'
  payload_off: 'OFF'
  retain: true

- platform: broadlink
  host: 10.10.20.5
  mac: '24:df:a7:4f:d1:94'
  type: rm4c_mini

- platform: broadlink
  host: 10.10.20.6
  mac: '24:df:a7:34:9b:3a'
  type: rm4c_mini
